### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by delboydell** [dale3h/alexa-smartstart#6]
Hi just found you and am wanting to give this a go, however the link 
3.Go to https://alexa-skills-server.herokuapp.com/smartstart and enter your Directed/Viper/Clifford/Python SmartStart username and password, as well as the skill ID that you copied from the previous step
looks like its down as it gives 404 down message.
I don't mind paying and was going to donate if it works.
please let me know either way.
thanks

**Comment by dale3h** [comment]
Hi @delboydell, thank you for bringing this to my attention. It appears that the card I had on my Heroku account was expired and could not be charged, so my Heroku account was suspended. I have updated  the payment information and it appears to now be back online.

Please give it a shot now and let me know if you run into any further issues.

**Comment by delboydell** [comment]
hi thanks for the quick response. The link now works and generates the text
boxes to be copied and pasted however I think the layout of the skill form
has changed and I cannot find where to paste the Intent Schema? I have the
option to add intent name call it viper, then it askes for the sample
utterances?
Any help would really be appreciated and a donation will be coming your way.
thanks
Phil
